### ISSUE TITLE
Segmentation fault at exiting

### ISSUE THREAD

**Issue by sagitter** [kazzmir/paintown#21]
Hello.

I'm successfully compiled `paintown` on `Fedora` and i will propose an rpm for including this game in the Fedora's official repository.

`paintown` looks working fine, but i'm getting a `Segmentation fault` when i close the game; this error is showed if i start paintown by terminal. The GDB output is:

```
[sagitter@Acer x86_64]$ gdb paintown-bin
GNU gdb (GDB) Fedora 8.0.1-36.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from paintown-bin...Reading symbols from /usr/lib/debug/usr/bin/paintown-bin-3.6.1-0.1.20180113git8a71ac8.fc27.x86_64.debug...done.
done.
(gdb) run -d /usr/share/paintown-3.6.1/data "$@"
Starting program: /usr/bin/paintown-bin -d /usr/share/paintown-3.6.1/data "$@"
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26-27.fc27.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[0:paintown] Give 'help' to see all the command line options.
[0:paintown] Debug level: 0
[0:paintown] Paintown version 3.6.1
[0:paintown] -- BEGIN init --
Data path is /usr/share/paintown-3.6.1/data/
Build date Mar 23 2018 11:25:48
[New Thread 0x7fffee8e5700 (LWP 19321)]
Allegro5 initialize Ok
Allegro5 version 5.2.0.1
Init image: Ok
Init primitives Ok
Init keyboard Ok
[New Thread 0x7fffe7515700 (LWP 19322)]
[New Thread 0x7fffe6d14700 (LWP 19323)]
Init joystick Ok
Init touch Failed
[New Thread 0x7fffe2513700 (LWP 19324)]
[New Thread 0x7fffe1d12700 (LWP 19325)]
[New Thread 0x7fffcce1b700 (LWP 19326)]
Set graphics mode: Ok
Initialize random number generator
[New Thread 0x7fffc4afd700 (LWP 19329)]
[New Thread 0x7fffbffff700 (LWP 19330)]
[New Thread 0x7fffbf7fe700 (LWP 19331)]
-- END init --
[0:paintown] Supported music extensions xm (extended module), s3m (scream tracker 3), mod (module), it (impulse tracker), nsf (nintendo sound file / famicom), spc (super nintendo / super famicom), gym (sega genesis / mega drive)
[New Thread 0x7fffbeffd700 (LWP 19332)]
[0:paintown] Unhandled menu attribute: 
[0:paintown]  Token: network-host
[0:paintown]   |--Token: name
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: English
[0:paintown]   |-- |-- |--Token: Network - Host
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Portuguese
[0:paintown]   |-- |-- |--Token: Hospedar na internet
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Français
[0:paintown]   |-- |-- |--Token: Réseaux - Hôte
[0:paintown]   |--Token: info
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: English
[0:paintown]   |-- |-- |--Token: Host a game that can be
played over the internet
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Portuguese
[0:paintown]   |-- |-- |--Token: Hospede um jogo para 
ser jogado na internet
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Français
[0:paintown]   |-- |-- |--Token: Etre l' hôte pour une partie réseaux
[0:paintown] Unhandled menu attribute: 
[0:paintown]  Token: network-join
[0:paintown]   |--Token: name
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: English
[0:paintown]   |-- |-- |--Token: Network - Join
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Русский
[0:paintown]   |-- |-- |--Token: Сеть - присоединится
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Français
[0:paintown]   |-- |-- |--Token: Connexion
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Portuguese
[0:paintown]   |-- |-- |--Token: Jogar on-line
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Deutsch
[0:paintown]   |-- |-- |--Token: Netzwerkspiel beitreten
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Español
[0:paintown]   |-- |-- |--Token: Network - Join
[0:paintown]   |--Token: info
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: English
[0:paintown]   |-- |-- |--Token: Join a game over the internet
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Русский
[0:paintown]   |-- |-- |--Token: Присоединится к игре через интернет
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Deutsch
[0:paintown]   |-- |-- |--Token: Einem Netzwerkspiel übers Internet beitreten
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Portuguese
[0:paintown]   |-- |-- |--Token: Jogue na internet com outras pessoas
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Français
[0:paintown]   |-- |-- |--Token: Rejoindre une partie sur internet
[0:paintown]   |-- |--Token: language
[0:paintown]   |-- |-- |--Token: Español
[0:paintown]   |-- |-- |--Token: Join a game over the internet
[0:paintown] Trying to load '/usr/share/paintown-3.6.1/data/music/aqua.s3m'
[0:paintown] Draw average 2ms
[0:paintown] Draw average 1ms
[0:paintown] Draw average 1ms
[0:paintown] Draw average 1ms
[0:paintown] Draw average 2ms
[0:paintown] Draw average 1ms
[0:paintown] Bye!
[Thread 0x7fffbeffd700 (LWP 19332) exited]

Thread 1 "paintown-bin" received signal SIGSEGV, Segmentation fault.
al_destroy_event_queue (queue=0x0) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/events.c:126
126	/usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/events.c: No such file or directory.
(gdb) thread apply all bt full

Thread 10 (Thread 0x7fffbf7fe700 (LWP 19331)):
#0  0x00007ffff685dbe6 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff6b0577d in _al_cond_timedwait (cond=cond@entry=0x7fffac000ba0, mutex=mutex@entry=0x7fffac000b70, timeout=timeout@entry=0x7fffbf7fda00) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/unix/uxthread.c:155
        unix_timeout = 0x7fffbf7fda00
        retcode = <optimized out>
#2  0x00007ffff6ac6d97 in do_wait_for_event (queue=queue@entry=0x7fffac000b20, ret_event=ret_event@entry=0x7fffbf7fda40, timeout=timeout@entry=0x7fffbf7fda00) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/events.c:470
        result = <optimized out>
        timed_out = false
        next_event = 0x0
#3  0x00007ffff6ac7367 in al_wait_for_event_timed (queue=queue@entry=0x7fffac000b20, ret_event=ret_event@entry=0x7fffbf7fda40, secs=secs@entry=0.0500000007) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/events.c:436
        timeout = {__pad1__ = 1521802636, __pad2__ = 304718000}
#4  0x0000555555672ab5 in System::do_timer (info=0x555555f2bfb0) at build/allegro5/r-tech1/out/release/system/allegro5/timer.cpp:28
        event = {type = 30, any = {type = 30, source = 0x555555f2f370, timestamp = 4.4461750000000002}, display = {type = 30, source = 0x555555f2f370, timestamp = 4.4461750000000002, x = 2, y = 0, width = 1291649024, 
            height = 1059155645, orientation = 0}, joystick = {type = 30, source = 0x555555f2f370, timestamp = 4.4461750000000002, id = 0x2, stick = 1291649024, axis = 1059155645, pos = 0, button = 0}, keyboard = {
            type = 30, source = 0x555555f2f370, timestamp = 4.4461750000000002, display = 0x2, keycode = 1291649024, unichar = 1059155645, modifiers = 0, repeat = false}, mouse = {type = 30, source = 0x555555f2f370, 
            timestamp = 4.4461750000000002, display = 0x2, x = 1291649024, y = 1059155645, z = 0, w = 0, dx = 0, dy = 0, dz = 0, dw = 0, button = 0, pressure = 0}, timer = {type = 30, source = 0x555555f2f370, 
            timestamp = 4.4461750000000002, count = 2, error = 0.00013299999999993872}, touch = {type = 30, source = 0x555555f2f370, timestamp = 4.4461750000000002, display = 0x2, id = 1291649024, x = 0.630595982, y = 0, 
            dx = 0, dy = 0, primary = false}, user = {type = 30, source = 0x555555f2f370, timestamp = 4.4461750000000002, __internal(double,...)(short, char, long double) = 0x2, data1 = 4549038857940434944, data2 = 0, 
            data3 = 0, data4 = 0}}
        source = <optimized out>
        queue = 0x7fffac000b20
#5  0x00007ffff6ace638 in thread_func_trampoline (inner=<optimized out>, _outer=0x555555f2b7a0) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/threads.c:80
        outer = 0x555555f2b7a0
        system = 0x555555d53100
#6  0x00007ffff6b055cb in thread_proc_trampoline (data=<optimized out>) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/unix/uxthread.c:44
        thread = <optimized out>
#7  0x00007ffff685750b in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#8  0x00007ffff57be16f in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 9 (Thread 0x7fffbffff700 (LWP 19330)):
#0  0x00007ffff685dbe6 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff6b0577d in _al_cond_timedwait (cond=cond@entry=0x7fffb4000ba0, mutex=mutex@entry=0x7fffb4000b70, timeout=timeout@entry=0x7fffbfffea00) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/unix/uxthread.c:155
        unix_timeout = 0x7fffbfffea00
        retcode = <optimized out>
#2  0x00007ffff6ac6d97 in do_wait_for_event (queue=queue@entry=0x7fffb4000b20, ret_event=ret_event@entry=0x7fffbfffea40, timeout=timeout@entry=0x7fffbfffea00) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/events.c:470
        result = <optimized out>
        timed_out = false
        next_event = 0x0
#3  0x00007ffff6ac7367 in al_wait_for_event_timed (queue=queue@entry=0x7fffb4000b20, ret_event=ret_event@entry=0x7fffbfffea40, secs=secs@entry=0.0500000007) at /usr/src/debug/allegro5-5.2.0-4.fc27.x86_64/src/events.c:436
        timeout = {__pad1__ = 1521802636, __pad2__ = 312751000}
#4  0x0000555555672ab5 in System::do_timer (info=0x555555d4c240) at build/allegro5/r-tech1/out/release/system/allegro5/timer.cpp:28
        event = {type = 30, any = {type = 30, source = 0x555555f2c230, timestamp = 5.40611}, display = {type = 30, source = 0x555555f2c230, timestamp = 5.40611, x = 148, y = 0, width = 49210368, height = 1058407717, 
            orientation = 0}, joystick = {type = 30, source = 0x555555f2c230, timestamp = 5.40611, id = 0x94, stick = 49210368, axis = 1058407717, pos = 0, button = 0}, keyboard = {type = 30, source = 0x555555f2c230, 
---Type <return> to continue, or q <return> to quit---q
timestamQuit
(gdb) quit
A debugging session is active.

	Inferior 1 [process 19317] will be killed.

Quit anyway? (y or n) y

```

**Comment by sagitter** [comment]
Code used:

paintown 8a71ac86c585d8029709a10865c0e97dc4d3d2d1
r-tech1 [6636b452f5a9b55d2831bcb74c23eb991c12ee50](https://github.com/kazzmir/r-tech1/tree/6636b452f5a9b55d2831bcb74c23eb991c12ee50)
allegro-5.2.0
gcc-7.3.1
